#!/bin/bash
# Test coverage using gcov & lcov
# download lcov  in http://ltp.sourceforge.net/coverage/lcov.php
#
# An adaptation of Patrick Pellissier's script in MPFR

if [[ $# -eq 0 ]]; then
  echo Usage: $0 srcdir [configure_options]
  exit 1;
fi

SRC_DIR=$1
if [ -z "$PKG" ]; then
  PKG="mpfr"
fi
DEST_DIR=/tmp/o$PKG-gcov
if [ -z "$TESTNAME" ]; then
  TESTNAME=$(cd $SRC_DIR; svn info|sed -n '/Revision: / p');
fi
echo $PKG " " $TESTNAME

# First Build MPFR in /tmp/
echo "Erasing previous " $DEST_DIR
rm -rf $DEST_DIR
mkdir $DEST_DIR

echo "Copying "$PKG" sources to "$DEST_DIR
cp $SRC_DIR/* $DEST_DIR 2>/dev/null
mkdir $DEST_DIR/tests
cp $SRC_DIR/tests/* $DEST_DIR/tests
mkdir $DEST_DIR/tests/data
cp $SRC_DIR/tests/data/* $DEST_DIR/tests/data
mkdir $DEST_DIR/m4
cp $SRC_DIR/m4/* $DEST_DIR/m4

cd $DEST_DIR
echo "Building "$PKG
./configure --enable-assert --disable-shared --enable-static \
  CFLAGS="-fprofile-arcs -ftest-coverage -g"
make check -j 4

# Then, make html pages
mkdir html
lcov -o html/$PKG.capture -t "$TESTNAME" -d . -c
lcov -o html/$PKG.info -r html/$PKG.capture {*/tests/*,*/gmp/*,abort_prec_max.c}
genhtml -o html --no-prefix -t "$TESTNAME" html/$PKG.info

echo "See results in "$DEST_DIR"/html/index.html"
