#!/bin/sh

# Check the format of the mpfrtests data file provided in argument or
# from the standard input.
# In case of error, run "sh -x vfy-data mpfrtests.data" for a trace.

set -e

[ -z "$1" ] || exec < "$1"

nxt=HOST
while read line
do
  : $line
  case "$line" in
    HOST:*)
      [ "$nxt" = HOST ]
      nxt=PROC
      ;;
    PROC:*)
      [ "$nxt" = PROC ]
      nxt=CHECK-BEGIN
      ;;
    CHECK-BEGIN*)
      [ "$nxt" = CHECK-BEGIN ]
      nxt=CONF
      ;;
    CONF:*)
      [ "$nxt" = CONF ]
      ;;
    INFO:*)
      [ "$nxt" = CONF ] || [ "$nxt" = INFO ]
      nxt=INFO
      ;;
    ENV:*|EVAL:*)
      [ "$nxt" = CONF ] || [ "$nxt" = INFO ]
      ;;
    CHECK-END)
      [ "$nxt" = INFO ]
      nxt=CHECK-BEGIN
      ;;
    \#*)
      # Comment
      continue
      ;;
    ?*)
      # Any unrecognized non-empty line
      exit 1
      ;;
    *)
      # Empty line
      [ "$nxt" = CHECK-BEGIN ] || [ "$nxt" = HOST ]
      nxt=HOST
      ;;
  esac
done
[ "$nxt" = CHECK-BEGIN ] || [ "$nxt" = HOST ]

# $Id: vfy-data 66746 2014-01-22 09:53:52Z vinc17/ypig $
